export interface SurgeryReference {
  name: string;
  severity: 'Menor' | 'Intermedia' | 'Mayor' | 'Compleja';
  bleedingRisk: 'Bajo' | 'Moderado' | 'Alto';
  estimatedLoss: string; // e.g. "< 100ml", "500-1000ml"
  description?: string;
}

export const SURGERY_DATABASE: SurgeryReference[] = [
  { name: 'Apendicectomía (Laparoscópica)', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Colecistectomía (Laparoscópica)', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Hernioplastia Inguinal', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Histerectomía Abdominal', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '200 - 500 ml' },
  { name: 'Reemplazo Total de Cadera', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '300 - 800 ml' },
  { name: 'Reemplazo Total de Rodilla', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '200 - 600 ml' },
  { name: 'Craneotomía (Tumor)', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 1500 ml' },
  { name: 'Bypass Coronario (CABG)', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '800 - 2000 ml' },
  { name: 'Resección Intestinal (Colectomía)', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Prostatectomía Radical', severity: 'Mayor', bleedingRisk: 'Alto', estimatedLoss: '500 - 1500 ml' },
  { name: 'Tiroidectomía', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Amigdalectomía', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
  { name: 'Biopsia de Mama', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '< 10 ml' },
  { name: 'Cirugía de Cataratas', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: 'Mínimo' },
  { name: 'Artroscopia de Rodilla', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Laminectomía', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 300 ml' },
  { name: 'Toracotomía', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 1000 ml' },
  { name: 'Esofagectomía', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 1500 ml' },
  { name: 'Gastrectomía Total', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '300 - 800 ml' },
  { name: 'Nefrectomía', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '200 - 500 ml' },
  { name: 'Cistectomía Radical', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 1500 ml' },
  { name: 'Cirugía de Columna (Multinivel)', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 2000 ml' },
  { name: 'Septoplastia', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Cirugía de Párpados (Blefaroplastia)', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '< 10 ml' },
  { name: 'Liposucción (> 5L)', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '200 - 500 ml' },
  { name: 'Abdominoplastia', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 300 ml' },
  { name: 'Mastopexia', severity: 'Mayor', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
  { name: 'Cirugía de Varices', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
  { name: 'Fistulectomía Anal', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '< 20 ml' },
  { name: 'Hemorroidectomía', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Artrodesis de Columna (1-2 niveles)', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '200 - 500 ml' },
  { name: 'Artrodesis de Columna (> 2 niveles)', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 1500 ml' },
  { name: 'Cirugía de Fontan', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: 'Variable (Alto)' },
  { name: 'Trasplante Renal', severity: 'Compleja', bleedingRisk: 'Moderado', estimatedLoss: '200 - 500 ml' },
  { name: 'Trasplante Hepático', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '1000 - 5000+ ml' },
  { name: 'Resección de Pulmón (Lobectomía)', severity: 'Compleja', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Neumonectomía', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '300 - 800 ml' },
  { name: 'Cirugía de Bentall', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '1000 - 2500 ml' },
  { name: 'Reparación de Aneurisma Aórtico (Abierto)', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '1000 - 3000 ml' },
  { name: 'Reparación de Aneurisma Aórtico (EVAR)', severity: 'Mayor', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
  { name: 'Endarterectomía Carotídea', severity: 'Mayor', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
  { name: 'Bypass Fémoro-Poplíteo', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 300 ml' },
  { name: 'Amputación Supracondílea', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Cirugía de Whipple', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 1500 ml' },
  { name: 'Pancreatectomía Distal', severity: 'Compleja', bleedingRisk: 'Moderado', estimatedLoss: '200 - 600 ml' },
  { name: 'Esplenectomía', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '200 - 500 ml' },
  { name: 'Cirugía Bariátrica (Bypass Gástrico)', severity: 'Mayor', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
  { name: 'Cirugía Bariátrica (Manga Gástrica)', severity: 'Mayor', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
  { name: 'Reducción de Fractura de Fémur', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '300 - 800 ml' },
  { name: 'Osteosíntesis de Radio/Cúbito', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Cirugía de Túnel Carpiano', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '< 10 ml' },
  { name: 'Drenaje de Absceso', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '< 20 ml' },
  { name: 'Desbridamiento de Herida', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
  { name: 'Apendicectomía Abierta', severity: 'Intermedia', bleedingRisk: 'Moderado', estimatedLoss: '50 - 150 ml' },
  { name: 'Colecistectomía Abierta', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 300 ml' },
  { name: 'Hernioplastia Incisional (Evisceración)', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Laparotomía Exploradora', severity: 'Mayor', bleedingRisk: 'Alto', estimatedLoss: '200 - 1000+ ml' },
  { name: 'Cirugía de Hartmann', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '200 - 500 ml' },
  { name: 'Cierre de Colostomía', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
  { name: 'Fijación de Fractura de Pelvis', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 2000+ ml' },
  { name: 'Reducción de Fractura de Tobillo', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Cirugía de Manguito Rotador', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Prótesis de Hombro', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '200 - 500 ml' },
  { name: 'Artroscopia de Hombro', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Cirugía de Columna (Microdiscectomía)', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Ventriculostomía (EVD)', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 20 ml' },
  { name: 'Derivación Ventrículo-Peritoneal (DVP)', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Evacuación de Hematoma Subdural', severity: 'Compleja', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Cirugía de Aneurisma Cerebral (Clipaje)', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '200 - 800 ml' },
  { name: 'Resección de Adenoma Hipofisario (Transesfenoidal)', severity: 'Mayor', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
  { name: 'Cirugía de Estrabismo', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '< 10 ml' },
  { name: 'Vitrectomía', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Timpanoplastia', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 20 ml' },
  { name: 'Mastoidectomía', severity: 'Mayor', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Laringectomía Total', severity: 'Compleja', bleedingRisk: 'Moderado', estimatedLoss: '200 - 500 ml' },
  { name: 'Parotidectomía', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Vaciamiento Ganglionar Cervical', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 300 ml' },
  { name: 'Cirugía de Mohs', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: 'Mínimo' },
  { name: 'Injerto de Piel (Grosor Parcial)', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '< 20 ml' },
  { name: 'Injerto de Piel (Grosor Total)', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Colgajo Libre (Microcirugía)', severity: 'Compleja', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Reducción Mamaria', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Aumento Mamario', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Orquidopexia', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '< 20 ml' },
  { name: 'Circuncisión', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '< 10 ml' },
  { name: 'Vasectomía', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '< 10 ml' },
  { name: 'RTU de Próstata (RTUP)', severity: 'Intermedia', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'RTU de Vejiga (RTUV)', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Ureteroscopia (Litotricia)', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 20 ml' },
  { name: 'Nefrolitotomía Percutánea (NLPC)', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 300 ml' },
  { name: 'Cesárea (Electiva)', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '400 - 700 ml' },
  { name: 'Cesárea (Urgencia)', severity: 'Mayor', bleedingRisk: 'Alto', estimatedLoss: '600 - 1200+ ml' },
  { name: 'Legrado Uterino (LUI)', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '20 - 100 ml' },
  { name: 'Salpingectomía (Ectópico)', severity: 'Intermedia', bleedingRisk: 'Moderado', estimatedLoss: '100 - 500+ ml' },
  { name: 'Miomectomía Abdominal', severity: 'Mayor', bleedingRisk: 'Alto', estimatedLoss: '300 - 1000+ ml' },
  { name: 'Miomectomía Laparoscópica', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Conización Cervical', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Cirugía de Fontan (Pediátrica)', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: 'Variable (Alto)' },
  { name: 'Cierre de Ductos Arterioso (PDA)', severity: 'Mayor', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Reparación de CIA / CIV', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '200 - 600 ml' },
  { name: 'Pleurodesis', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Pleurectomía', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '200 - 600 ml' },
  { name: 'Mediastinoscopia', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 20 ml' },
  { name: 'Cirugía de Hiato (Nissen)', severity: 'Mayor', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
  { name: 'Esplenectomía Laparoscópica', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Adrenalectomía Laparoscópica', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Tiroidectomía Total', severity: 'Mayor', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
  { name: 'Paratiroidectomía', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Amputación de Dedo', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '< 20 ml' },
  { name: 'Amputación Infracondílea', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Fasciectomía (Dupuytren)', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Tenoplastia', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '< 20 ml' },
  { name: 'Osteotomía de Hallux Valgus', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  // Maxilofacial
  { name: 'Fractura Lefort I/II/III', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '200 - 600 ml' },
  { name: 'Mandibulectomía con Reconstrucción', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 1500 ml' },
  { name: 'Cirugía Ortognática Bimaxilar', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '200 - 500 ml' },
  // Pediátrica Especializada
  { name: 'Atresia de Esófago (Reparación)', severity: 'Compleja', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Onfalocele / Gastrosquisis (Cierre)', severity: 'Compleja', bleedingRisk: 'Moderado', estimatedLoss: 'Variable' },
  { name: 'Mielomeningocele (Cierre)', severity: 'Compleja', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Estenosis Pilórica (Piloromiotomía)', severity: 'Intermedia', bleedingRisk: 'Bajo', estimatedLoss: '< 10 ml' },
  // Neurocirugía Avanzada
  { name: 'Resección de MAV Cerebral', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 2000 ml' },
  { name: 'Estimulación Cerebral Profunda (DBS)', severity: 'Compleja', bleedingRisk: 'Bajo', estimatedLoss: '< 50 ml' },
  { name: 'Resección de Tumor de Fosa Posterior', severity: 'Compleja', bleedingRisk: 'Moderado', estimatedLoss: '200 - 800 ml' },
  { name: 'Hemisferectomía', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 1500 ml' },
  // Cardiovascular Avanzada
  { name: 'Trasplante Cardíaco', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '1000 - 3000 ml' },
  { name: 'Trasplante Pulmonar (Unilateral/Bilateral)', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '1000 - 4000 ml' },
  { name: 'Reparación / Reemplazo Valvular Mitral', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 1500 ml' },
  { name: 'Cirugía de Ross', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '800 - 2000 ml' },
  { name: 'Asistencia Ventricular (LVAD)', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '1000 - 3000 ml' },
  // Vascular Avanzada
  { name: 'Bypass Aorto-Bifemoral', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 1500 ml' },
  { name: 'Trombectomía Arterial Aguda', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Cirugía de Varices (Radiofrecuencia/Láser)', severity: 'Menor', bleedingRisk: 'Bajo', estimatedLoss: '< 20 ml' },
  // Oncología Avanzada
  { name: 'HIPEC (Quimioterapia Intraperitoneal Hipertérmica)', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 2000 ml' },
  { name: 'Pelvectomía Exenterativa', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '1000 - 4000 ml' },
  { name: 'Resección de Sarcoma Retroperitoneal', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 2500 ml' },
  { name: 'Hemipelvectomía', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '1000 - 3000 ml' },
  // Ortopedia Compleja
  { name: 'Revisión de Prótesis de Cadera (Sepsis/Aflojamiento)', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 2000 ml' },
  { name: 'Revisión de Prótesis de Rodilla', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '300 - 1000 ml' },
  { name: 'Artrodesis de Tobillo', severity: 'Mayor', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
  { name: 'Alargamiento Óseo (Ilizarov)', severity: 'Mayor', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
  // Urología Avanzada
  { name: 'Nefrectomía Parcial (Robótica/Laparoscópica)', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Linfadenectomía Retroperitoneal', severity: 'Compleja', bleedingRisk: 'Moderado', estimatedLoss: '200 - 800 ml' },
  // Ginecología Avanzada
  { name: 'Linfadenectomía Pélvica y Paraaórtica', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Traquelectomía Radical', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '200 - 500 ml' },
  // Otras
  { name: 'Cirugía de Citorreducción (Ovario)', severity: 'Compleja', bleedingRisk: 'Alto', estimatedLoss: '500 - 2000 ml' },
  { name: 'Reconstrucción de Tránsito Intestinal', severity: 'Mayor', bleedingRisk: 'Moderado', estimatedLoss: '100 - 400 ml' },
  { name: 'Hernioplastia Hiatal Paraesofágica', severity: 'Mayor', bleedingRisk: 'Bajo', estimatedLoss: '< 100 ml' },
];
